spring:
  profiles:
    active: dev
logging:
  config: classpath:config/logback-spring.xml
#server:
#  tomcat:
#    accesslog:
#      enabled: true
#      directory: D:\springBootLog\tomcat_logs
#      buffered: true
##      file-date-format: .yyyy-MM-dd
#      pattern: common
#      prefix: access_log
#      rename-on-rotate: false
#      request-attributes-enabled: false
#      rotate: true
#      suffix: .log
